sudo: false
language: java
notifications:
  email: false

services:
  - docker

before_cache:
  - rm -rf $HOME/.m2/repository/io/jenkins/configuration-as-code*

cache:
  directories:
    - $HOME/.m2

env:
  global:
    - JAVA_LEVEL=8

# No need to build on release commits from maven-release-plugin
if: |
  commit_message !~ /\[maven-release-plugin\]/

matrix:
  include:
    - jdk: openjdk11
      env:
        - MVN_FLAG='-Djenkins.version=2.164.1 -Daccess-modifier-checker.failOnError=true'
    - jdk: openjdk8
      env:
        - MVN_FLAG='-Djenkins.version=2.164.1 -Daccess-modifier-checker.failOnError=true'
    - jdk: openjdk8
      env:
        - SHIPPABLE=true

install:
  - ".travis/run.sh install"
script:
  - ".travis/run.sh"
deploy:
  - provider: script
    skip_cleanup: true
    script: ".travis/run.sh"
    on:
      branch: testRelease
      repo: jenkinsci/configuration-as-code-plugin
      jdk: openjdk8
      condition: "$SHIPPABLE = true"
